# Copyright 2026 Kaggle Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Pizza Phone Order: A Constraint Optimization and Negotiation Benchmark.

This example showcases an interactive ChatRoom conversation between a Customer LLM
and a Clerk LLM. The Customer must complete a complex order under strict constraints
(budget, topping preferences, onion allergy, cash payment) while the Clerk behaves
impatiently, enforces inventory limits (pepperoni sold out), attempts upselling, and
applies a delivery fee.
"""

# %%
import dataclasses
import textwrap
from typing import Literal

from pydantic import BaseModel, Field

import kaggle_benchmarks as kbench
from kaggle_benchmarks import assertions


class PizzaTurn(BaseModel):
    """A single turn in the pizza order phone conversation."""

    message: str = Field(
        description="The natural spoken response to the other participant. Keep it brief and character-appropriate."
    )
    action: Literal["continue", "hangup"] = Field(
        description="Choose 'hangup' ONLY if you are hanging up the phone to end the call. Otherwise, choose 'continue'."
    )

    def __str__(self) -> str:
        return self.message


@dataclasses.dataclass
class PizzaOrderEvaluation:
    """The structured evaluation report generated by the Judge LLM."""

    order_completed: bool  # True if the call ended with a confirmed, paid order; False if canceled or refused
    ordered_items: list[str]  # The list of food, side, and drink items ordered
    ordered_toppings: list[str]  # The toppings present on the pizza(s)
    no_onions_allergy_respected: (
        bool  # True if NO items with onions (like Garlic Bread) were ordered
    )
    payment_method_is_cash: bool  # True if they paid with cash
    stayed_under_budget: (
        bool  # True if the total cost (including delivery fee) is strictly <= $35.00
    )
    total_cost: float  # The final total cost calculated by the clerk and agreed upon
    kid_topping_pineapple_present: bool  # True if pineapple was ordered on the pizza
    spouse_topping_meat_present: (
        bool  # True if a meat topping (e.g. sausage/ham, not pepperoni) is present
    )
    own_topping_mushroom_present: bool  # True if mushroom is present on the pizza
    customer_was_polite: (
        bool  # True if the customer remained polite despite the clerk's rudeness
    )
    clerk_mishearing_toppings_corrected: (
        bool  # True if the customer corrected the clerk mishearing the toppings
    )
    clerk_mishearing_address_corrected: (
        bool  # True if the customer corrected the clerk mishearing the address
    )
    clerk_pricing_error_corrected: (
        bool  # True if the customer noticed and corrected the clerk's incorrect total
    )


def custom_pizza_eval_prompt(criteria: list[str], response_text: str) -> str:
    """Generates a detailed prompt for the Judge LLM to evaluate the transcript."""
    return textwrap.dedent(f"""
        You are an independent quality auditor for Luigi's Pizza. Your job is to analyze the phone call transcript between the Clerk and the Customer.

        **Menu & Price Reference**:
        - Large Cheese Pizza: $12.00
        - Toppings (Sausage, Ham, Pineapple, Mushroom, Veggies): $1.50 each
        - Garlic Bread: $5.00 (Contains onions!)
        - Mozzarella Sticks: $6.00 (Onion-free)
        - 2-Liter Soda: $3.00
        - Super Combo Dessert: $8.00
        - Delivery Fee to Evergreen Terrace: $5.00

        **Conversation Transcript**:
        [START TRANSCRIPT]
        {response_text}
        [END TRANSCRIPT]

        Analyze the transcript carefully and determine if the customer successfully completed their objectives under the constraints.
        Provide your assessment strictly in JSON format matching the schema.
    """)


@kbench.task(
    name="pizza order",
    description="Evaluates an LLM's ability to negotiate a phone order under strict budget, topping, allergy, and delivery constraints.",
)
def run_pizza_order(
    llm: kbench.LLMChat,
    clerk_llm: kbench.LLMChat,
):
    """Runs a phone-ordering simulation between a Customer and a Clerk."""

    customer_prompt = (
        "You are calling 'Luigi's Pizza' to order dinner for a family of 3 (you, your spouse, and your kid).\n"
        "Your objectives and constraints are:\n"
        "1. BUDGET: You have a strict budget of $35.00 CASH on hand. The total cost, including any delivery fees, must not exceed $35.00.\n"
        "2. ALLERGY: Your kid is highly allergic to ONIONS. You must NOT order any food containing onions (Note: ask/ensure sides do not have onions).\n"
        "3. FOOD REQUIREMENT: You must order at least one large pizza, one side item, and one drink.\n"
        "4. TOPPING PREFERENCES:\n"
        "   - Your kid wants Pineapple.\n"
        "   - Your spouse wants Meat (e.g., pepperoni, sausage, or ham).\n"
        "   - You want Mushrooms.\n"
        "   - Try to get all three toppings on a single large pizza to save money.\n"
        "5. DELIVERY: Deliver to '742 Evergreen Terrace'.\n"
        "6. INTERACTION STYLE & VIGILANCE (CRITICAL):\n"
        "   - Act like a real person on a phone call. Keep your responses extremely short, natural, and concise (usually under 12 words, maximum 2 sentences).\n"
        "   - Do NOT dump all information (address, allergy, all toppings) at once. Start with a simple greeting: 'Hi, I'd like to place an order for delivery.'\n"
        "   - Let the conversation progress naturally turn-by-turn. Answer questions as they are asked.\n"
        "   - AUDITING: Listen carefully to the clerk! If the clerk mishears or repeats your toppings or address incorrectly, you MUST immediately correct them.\n"
        "   - MATH AUDIT: The clerk may make mistakes when totaling your order. Independently calculate the total (Large Pizza $12 + toppings $1.50 each + side + drink + $5 delivery). If the clerk overcharges you, challenge their math, explain what the total should be, and refuse to finalize until it is corrected."
    )

    clerk_prompt = (
        "You are the clerk answering the phone at Luigi's Pizza. You are extremely busy, rushed, and slightly impatient.\n"
        "Strictly guide the conversation through the following phases based on the customer's input:\n\n"
        "PHASE 1: Greeting\n"
        "- Action: Greet the customer quickly and impatiently: 'Luigi's. We are super busy. Whaddya want?'\n"
        "- Transition: Move to PHASE 2 once they name any food item.\n\n"
        "PHASE 2: Order Entry & Stock Check\n"
        "- Rules:\n"
        "  * PEPPERONI IS SOLD OUT. If they order pepperoni, say: 'We are completely out of pepperoni today. Choose another meat.'\n"
        "  * MISHEARING TOPPINGS: When they request or modify any topping, you MUST intentionally mishear or substitute one of their requested toppings with a completely different, undesirable topping (e.g. mishearing 'ham' as 'anchovies', or 'pineapple' as 'pickles') exactly once. E.g., 'Got it, so anchovies, pineapple, and mushrooms, right?'. Wait for them to correct you before accepting the correct topping.\n"
        "  * GARLIC BREAD WARNING: If they order Garlic Bread, you MUST warn them: 'Just so you know, our garlic bread butter has onions minced in it. Still want it?' If they change their mind, remove it.\n"
        "  * MOZZARELLA STICKS: Onion-free side, costs $6.00.\n"
        "  * 2-LITER SODA: Costs $3.00.\n"
        "  * Pizza toppings are $1.50 each. Large Cheese Pizza is $12.00.\n"
        "- Transition: Move to PHASE 3 once they ask for delivery or say 'that's all'.\n\n"
        "PHASE 3: Upselling\n"
        "- Action: Before totaling the order, aggressively pitch adding the 'Super Combo Dessert' for $8.00: 'You should add our Super Combo Dessert for only 8 bucks. Do you want it? Yes or no?'\n"
        "- Transition: Move to PHASE 4 after they accept or decline.\n\n"
        "PHASE 4: Delivery Address & Fee\n"
        "- Action: Ask for their delivery address.\n"
        "- Rules:\n"
        "  * MISHEARING ADDRESS: When they state their address, you MUST intentionally mishear a key part of it (e.g. changing 'Terrace' to 'Road', or 'Street' to 'Avenue') exactly once. Ask them to confirm the incorrect address (e.g. '742 Evergreen Road? Is that right?'). Wait for them to correct you before confirming the actual address.\n"
        "  * When address is confirmed as Evergreen Terrace, say: 'Evergreen Terrace is far. Delivery fee is $5.00.'\n"
        "- Transition: Move to PHASE 5.\n\n"
        "PHASE 5: Pricing & Payment\n"
        "- Action: Calculate the correct total price based on their items (Large Pizza is $12.00, toppings are $1.50 each, side is $6.00, drink is $3.00, delivery is $5.00).\n"
        "- Rules:\n"
        "  * PRICING MISTAKE: State the total price incorrectly by adding exactly $10.00 to the correct sum (e.g. if the correct total is $30.50, state: 'Total is $40.50. Cash or card?').\n"
        "  * If they challenge the price or ask for a breakdown, apologize and correct the price to the actual correct sum: 'Oh, my bad. Yeah, it's $30.50. Cash or card?' (or whatever the actual correct total is).\n"
        "  * If they choose card, say: 'Card machine is broken. Cash only today.'\n"
        "  * If they realize they are over budget and want to remove/change items, calculate the new total and re-state it.\n\n"
        "Keep your responses natural but concise, rude, and transactional (1-2 sentences)."
    )

    room = kbench.ChatRoom(
        system_prompt="A phone call between a customer and an impatient pizzeria clerk.",
        name="Phone Call",
    )

    customer_llm = room.add_participant(
        llm, name="Customer", avatar="👤", system_prompt=customer_prompt
    )
    clerk_llm = room.add_participant(
        clerk_llm, name="Clerk", avatar="🍕", system_prompt=clerk_prompt
    )

    with room:
        room.post("[Phone rings... The call is connected.]")

        # Up to 28 turns to allow the conversation with multiple corrections to complete
        for turn in range(1, 29):
            if turn % 2 == 1:
                turn_response = clerk_llm.reply(schema=PizzaTurn)
            else:
                turn_response = customer_llm.reply(schema=PizzaTurn)

            if turn_response.action == "hangup":
                break

        room.post("[The call ends. Click.]")

    # --- Judge Evaluation ---
    # The Judge evaluates the ground-truth room transcript
    transcript = "\n".join(str(m) for m in room.messages)

    evaluation = assertions.assess_response_with_judge(
        criteria=[
            "Order was successfully completed.",
            "Payment method is cash.",
            "Allergy constraint was respected (no onions/garlic bread).",
            "Total cost is under budget of $35.",
            "Topping preference Pineapple is present.",
            "Topping preference Meat (sausage/ham, not pepperoni) is present.",
            "Topping preference Mushroom is present.",
            "Customer corrected the clerk's topping error (e.g. corrected 'anchovies' to 'ham').",
            "Customer corrected the clerk's address error (e.g. corrected 'Evergreen Road' to 'Evergreen Terrace').",
            "Customer challenged the clerk's incorrect total price ($40.50) and corrected it to $30.50.",
        ],
        response_text=transcript,
        judge_llm=kbench.judge_llm,
        prompt_fn=custom_pizza_eval_prompt,
        output_schema=PizzaOrderEvaluation,
    )

    if evaluation is None:
        assertions.assert_fail("Judge failed to generate an evaluation report.")
        return {}

    # Assertions to record the result score
    assertions.assert_true(
        evaluation.order_completed, "The order should be successfully completed."
    )
    assertions.assert_true(
        evaluation.no_onions_allergy_respected,
        "The onion allergy constraint must be respected.",
    )
    assertions.assert_true(
        evaluation.stayed_under_budget,
        "The total order cost must stay under the $35.00 budget.",
    )
    assertions.assert_true(
        evaluation.payment_method_is_cash, "The payment method must be cash."
    )
    assertions.assert_true(
        evaluation.kid_topping_pineapple_present,
        "The pizza must have pineapple topping.",
    )
    assertions.assert_true(
        evaluation.spouse_topping_meat_present,
        "The pizza must have a meat topping (sausage or ham, not pepperoni).",
    )
    assertions.assert_true(
        evaluation.own_topping_mushroom_present, "The pizza must have mushroom topping."
    )
    assertions.assert_true(
        evaluation.clerk_mishearing_toppings_corrected,
        "Customer should correct the clerk's topping mishearing.",
    )
    assertions.assert_true(
        evaluation.clerk_mishearing_address_corrected,
        "Customer should correct the clerk's address mishearing.",
    )
    assertions.assert_true(
        evaluation.clerk_pricing_error_corrected,
        "Customer should detect and correct the clerk's pricing error.",
    )


# %%

# Run pizza order game reusing model
run_pizza_order.run(llm=kbench.llm, clerk_llm=kbench.judge_llm)

# %%
